### PR TITLE
Redo the file viewing GUI

### PR DESCRIPTION
**Pull request by skybird23333**
This pull request aims to replace the current static Github pages with a front end VueJS application which uses naive-ui. It resolves issues the existing page such as loading times(the entire index is loaded at once) and and I plan to add the following features:
- Look nicer(done)
- File browser like the nice one mentioned in #1(done)
~~- Download multiple files at once~~ I might just do this for another PR, I want to just get the basic website up
- Can't think of more

### CODE REVIEW

**Comment by skybird23333** [comment]
image
Current version in action(yes the layout is a bit very broken)

**Comment by wace-vault** [comment]
Wonderful, thanks for taking the time to do this. Looks great! A few things which need to be checked off before going public:

- [ ] Maintainability - build steps & hosting. Are we deploying statically to Vercel/GH Pages, or is there a router involved (doesn't seem like it given your commits) - if a router _is_ involved, can we use SSR only?
- [ ] On that note, if it were possible to get a [live build going](https://vitejs.dev/guide/static-deploy.html), that'd be amazing. Pages is preferable but Vercel obviously works.
- [ ] Bulk downloading. This PR creates a great UI but bulk downloading is still a little difficult, and is more an issue with the hosting provider IMO - GH will rate limit any attempt to download files quickly, and only offers bulk zip download of the whole repo. If you have any ideas towards implementation let us know.
- [ ] #2 should be pretty easy to integrate into this UI. Definitely something to keep in mind for the future.

Again, thanks for your time working on this and it's a v positive first step. Happy to chat further privately as well, if you drop a contact address.

**Comment by wace-vault** [comment]
Hi, planning to reply in DM's. Can't seem to add you on Discord, are you sure your handle is correct?

**Comment by skybird23333** [comment]
> Hi, planning to reply in DM's. Can't seem to add you on Discord, are you sure your handle is correct?

@wace-vault Apologies, it should be skybird2333#3209.

**Comment by skybird23333** [comment]
The site for this PR is now viewable at https://skybird23333.github.io/collection/

**Comment by skybird23333** [comment]
Coming back to this - I think the website should be good to go now.

**Comment by wace-vault** [comment]
> Coming back to this - I think the website should be good to go now.

Thanks for all of this! Only problem I can see currently is PNGs and JPGs/JPEGs are treated as text files rather than being displayed, but if you can't be bothered fixing that I'm happy to merge.

It seems like bulk downloading won't really be possible with GitHub?

**Comment by skybird23333** [comment]
> Thanks for all of this! Only problem I can see currently is PNGs and JPGs/JPEGs are treated as text files rather than being displayed, but if you can't be bothered fixing that I'm happy to merge.

During development I haven't really noticed image files in the repository as they are mostly doc or pdf and so I ignored that. Can you show me where those are?

> It seems like bulk downloading won't really be possible with GitHub?

There are a number of implementations I have considered but it seems with Github it is just limited, I will look further into this and open a PR for it in the future.

**Comment by wace-vault** [comment]
Here's a few locations of PNGs:
```
./applications/y12/notes/piecewise graphs.png
./chemistry/y11/notes/Acids and bases/some y11 acid notes part 1.png
./chemistry/y11/notes/Acids and bases/some y11 acids notes part 2.png
./chemistry/y11/notes/Aqueous solutions/some y11 solubility notes part 1.png
./chemistry/y11/notes/Aqueous solutions/some y11 solubility notes part 2.png
./chemistry/y11/notes/Aqueous solutions/some y11 water notes.png
./chemistry/y11/notes/Calculations/stoich.png
./chemistry/y11/notes/IMF/some y11 imf notes.png
```
As for the bulk downloading that's fine, we can merge this then work on that later.
Thanks for all the help.

**Comment by skybird23333** [comment]
Fixed image previewing.

**Comment by wace-vault** [comment]
Looks great so far, thanks for all the help! I'll merge now.

**Pull request merged**
